# Generated by Django 6.0.1 on 2026-04-14 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_cedula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rol', models.CharField(choices=[('Agricultor', 'Agricultor'), ('Fumigador', 'Fumigador'), ('Recolector', 'Recolector'), ('Varios', 'Varios')], default='Varios', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadTiempo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_Actividad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id_ciclo', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cantidad_produccion', models.FloatField(help_text='Cantidad cosechada en Kg')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_ciclo3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CicloActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('numero_personas', models.IntegerField()),
                ('color', models.CharField(default='#000000', max_length=20)),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_CicloActividad2', to='managecultivo.actividad')),
                ('id_ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_CicloActividad1', to='managecultivo.ciclo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_CicloActividad3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id_cultivo', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('tiempo_agricola', models.IntegerField(help_text='Tiempo en días')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_Cultivo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ciclo',
            name='id_cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_ciclo1', to='managecultivo.cultivo'),
        ),
        migrations.CreateModel(
            name='CultivoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_inicio', models.IntegerField(default=1)),
                ('numero_personas', models.IntegerField()),
                ('color', models.CharField(default='#000000', max_length=20)),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_cultivoactividad2', to='managecultivo.actividad')),
                ('id_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_cultivoactividad', to='managecultivo.cultivo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_cultivoactividad4', to=settings.AUTH_USER_MODEL)),
                ('frecuencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_cultivoactividad3', to='managecultivo.unidadtiempo')),
            ],
            options={
                'ordering': ['dia_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad_existente', models.FloatField()),
                ('tipo', models.CharField(choices=[('fertilizante', 'Fertilizante'), ('semilla', 'Semilla'), ('herramienta', 'Herramienta')], default='fertilizante', max_length=20)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_insumos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CultivoActividadInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sugerida', models.FloatField(help_text='Cantidad requerida para la actividad')),
                ('actividad_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_CultivoActividadInsumo1', to='managecultivo.cultivoactividad')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_CultivoActividadInsumo2', to=settings.AUTH_USER_MODEL)),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_CultivoActividadInsumo2', to='managecultivo.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='CompraInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('marca', models.CharField(max_length=50)),
                ('cantidad', models.FloatField()),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_CompraInsumo2', to=settings.AUTH_USER_MODEL)),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_CompraInsumo1', to='managecultivo.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='CicloActividadInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.FloatField(help_text='Cantidad real utilizada en Kg')),
                ('actividad_ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_CCicloActividadInsumo1', to='managecultivo.cicloactividad')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_CCicloActividadInsumo3', to=settings.AUTH_USER_MODEL)),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_CCicloActividadInsumo2', to='managecultivo.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='CicloActividadPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_CicloActividadPersonal1', to='managecultivo.cicloactividad')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_CicloActividadPersonal2', to='managecultivo.personal')),
            ],
        ),
        migrations.CreateModel(
            name='ZonaAgricola',
            fields=[
                ('id_zonaagricola', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fk_ZonaAgricola', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ciclo',
            name='id_zonaagricola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_ciclo2', to='managecultivo.zonaagricola'),
        ),
    ]
