# Generated by Django 6.0.1 on 2026-04-08 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_cedula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rol', models.CharField(choices=[('Agricultor', 'Agricultor'), ('Fumigador', 'Fumigador'), ('Recolector', 'Recolector'), ('Varios', 'Varios')], default='Varios', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadTiempo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id_ciclo', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cantidad_produccion', models.FloatField(help_text='Cantidad cosechada en Kg')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadCiclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('numero_personas', models.IntegerField()),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecultivo.actividad')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecultivo.ciclo')),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id_cultivo', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('tiempo_agricola', models.IntegerField(help_text='Tiempo en días')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ciclo',
            name='id_cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecultivo.cultivo'),
        ),
        migrations.CreateModel(
            name='ActividadCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_veces', models.IntegerField()),
                ('frecuencia_valor', models.IntegerField()),
                ('frecuencia', models.IntegerField(help_text='Frecuencia en días')),
                ('numero_personas', models.IntegerField()),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecultivo.actividad')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecultivo.cultivo')),
                ('frecuencia_unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frecuencias', to='managecultivo.unidadtiempo')),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad_existente', models.FloatField()),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompraInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField()),
                ('marca', models.CharField(max_length=50)),
                ('cantidad', models.FloatField()),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecultivo.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadCultivoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sugerida', models.FloatField(help_text='Cantidad requerida para la actividad')),
                ('actividad_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecultivo.actividadcultivo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecultivo.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadCicloInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.FloatField(help_text='Cantidad real utilizada en Kg')),
                ('actividad_ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecultivo.actividadciclo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecultivo.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadCicloPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecultivo.actividadciclo')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecultivo.personal')),
            ],
        ),
        migrations.CreateModel(
            name='ZonaAgricola',
            fields=[
                ('id_zonaagricola', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ciclo',
            name='id_zonaagricola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managecultivo.zonaagricola'),
        ),
    ]
