# Generated by Django 6.0.1 on 2026-04-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managecultivo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadcultivo',
            name='frecuencia',
        ),
    ]
