# Generated by Django 6.0.1 on 2026-04-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecultivo', '0002_remove_actividadcultivo_frecuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='tipo',
            field=models.CharField(choices=[('fertilizante', 'Fertilizante'), ('semilla', 'Semilla'), ('herramienta', 'Herramienta')], default='fertilizante', max_length=20),
        ),
    ]
