# Generated by Django 6.0.1 on 2026-04-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecultivo', '0003_insumo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadcultivo',
            name='a_partir_de',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actividadcultivo',
            name='color',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
