# Generated by Django 6.0.1 on 2026-04-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managecultivo', '0004_actividadcultivo_a_partir_de_actividadcultivo_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadciclo',
            name='color',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
